-- ============================================================
-- JaringLokal (AerLaut) — Database Schema & Seed Data (SATU FILE)
-- Supabase Auth Edition (Password hashing bcrypt otomatis)
-- ============================================================
-- File ini adalah GABUNGAN dari seluruh script SQL project
-- (skema tabel, trigger, RLS, realtime, dan data contoh).
--
-- CARA PAKAI — pilih salah satu skenario:
--
-- (A) PROJECT SUPABASE BARU / KOSONG:
--     Jalankan SELURUH file ini dari atas ke bawah, satu kali,
--     di Supabase Dashboard → SQL Editor.
--
-- (B) DATABASE SUDAH BERJALAN (tabel users/stores/products/orders
--     sudah ada, seperti project yang sekarang dipakai untuk demo):
--     Jalankan HANYA bagian "BAGIAN 6: MIGRASI UNTUK DATABASE
--     YANG SUDAH LIVE" di paling bawah file ini. Bagian itu berisi
--     kolom & tabel baru (order_chats, support_tickets, kolom
--     escrow di orders) plus RLS yang sebelumnya belum ada —
--     aman dijalankan berkali-kali (pakai IF NOT EXISTS / DROP
--     POLICY IF EXISTS, tidak akan error atau membuat data ganda).
--
--     Setelah itu, "BAGIAN 5: SEED DATA DEMO" juga aman dijalankan
--     ulang kapan saja kalau butuh menambah data contoh.
-- ============================================================

-- ============================================================
-- BAGIAN 1: TABEL-TABEL UTAMA
-- ============================================================

-- ------------------------------------------------------------
-- 1a. public.users — Profile extension dari auth.users
--     id = UUID dari auth.users (bukan auto-increment)
--     TIDAK ada kolom password — dikelola Supabase Auth (bcrypt)
-- ------------------------------------------------------------
CREATE TABLE public.users (
  id         UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name       TEXT        NOT NULL DEFAULT '',
  email      TEXT        NOT NULL UNIQUE,
  phone      TEXT        NOT NULL DEFAULT '',
  role       TEXT        NOT NULL DEFAULT 'customer'
               CHECK (role IN ('customer', 'seller', 'admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_email ON public.users (email);
CREATE INDEX idx_users_role  ON public.users (role);
CREATE INDEX idx_users_phone ON public.users (phone);

-- ------------------------------------------------------------
-- 1b. public.stores — Toko Penjual
-- ------------------------------------------------------------
CREATE TABLE public.stores (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID        REFERENCES public.users(id) ON DELETE CASCADE,
  store_name  TEXT        NOT NULL,
  description TEXT,
  address     TEXT,
  phone       TEXT,
  status      TEXT        NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_stores_user_id ON public.stores (user_id);
CREATE INDEX idx_stores_status  ON public.stores (status);

-- ------------------------------------------------------------
-- 1c. public.products — Katalog Produk
-- ------------------------------------------------------------
CREATE TABLE public.products (
  id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id   BIGINT      REFERENCES public.stores(id) ON DELETE SET NULL,
  store_name TEXT        NOT NULL DEFAULT 'Toko Nelayan',
  name       TEXT        NOT NULL,
  price      NUMERIC     NOT NULL CHECK (price >= 0),
  category   TEXT        NOT NULL,
  stock      INT         NOT NULL DEFAULT 0 CHECK (stock >= 0),
  image      TEXT,
  unit       TEXT        NOT NULL DEFAULT 'kg',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_products_store_id ON public.products (store_id);
CREATE INDEX idx_products_category ON public.products (category);

-- ------------------------------------------------------------
-- 1d. public.orders — Pesanan Pelanggan
-- ------------------------------------------------------------
CREATE TABLE public.orders (
  id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  user_name      TEXT        NOT NULL DEFAULT 'Pelanggan',
  seller_id      UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  store_id       BIGINT      REFERENCES public.stores(id) ON DELETE SET NULL,
  store_name     TEXT,
  total_amount   NUMERIC     NOT NULL CHECK (total_amount >= 0),
  shipping_fee   NUMERIC     NOT NULL DEFAULT 0,
  status         TEXT        NOT NULL DEFAULT 'Menunggu Konfirmasi',
  escrow_status  TEXT        NOT NULL DEFAULT 'pending_payment',
  items          JSONB       NOT NULL DEFAULT '[]',
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_orders_user_id   ON public.orders (user_id);
CREATE INDEX idx_orders_seller_id ON public.orders (seller_id);
CREATE INDEX idx_orders_store_id  ON public.orders (store_id);
CREATE INDEX idx_orders_status    ON public.orders (status);
CREATE INDEX idx_orders_created   ON public.orders (created_at DESC);

-- ------------------------------------------------------------
-- 1e. public.user_logs — Log Aktivitas & Demografi Pengunjung
-- ------------------------------------------------------------
CREATE TABLE public.user_logs (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  user_name   TEXT        NOT NULL DEFAULT 'Pengunjung',
  action      TEXT        NOT NULL, -- 'login' | 'register' | 'purchase' | 'page_view'
  ip_address  TEXT,
  city        TEXT,
  region      TEXT,
  country     TEXT,
  device_type TEXT,                 -- 'Mobile' | 'Desktop' | 'Tablet'
  metadata    JSONB       NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_user_logs_user_id    ON public.user_logs (user_id);
CREATE INDEX idx_user_logs_action     ON public.user_logs (action);
CREATE INDEX idx_user_logs_created_at ON public.user_logs (created_at DESC);

-- ------------------------------------------------------------
-- 1f. public.order_chats — Ruang Chat 3 Pihak per Pesanan
--     (buyer, seller, admin berkomunikasi dalam 1 pesanan)
-- ------------------------------------------------------------
CREATE TABLE public.order_chats (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    BIGINT      NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  sender_id   UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  sender_name TEXT        NOT NULL DEFAULT 'Pengguna',
  sender_role TEXT        NOT NULL DEFAULT 'buyer', -- 'buyer' | 'seller' | 'admin' | 'system'
  text        TEXT        NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_order_chats_order_id ON public.order_chats (order_id);

-- ------------------------------------------------------------
-- 1g. public.support_tickets — Tiket Dukungan Pelanggan/Tamu
-- ------------------------------------------------------------
CREATE TABLE public.support_tickets (
  id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_code        TEXT        NOT NULL UNIQUE,
  user_id            UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  name               TEXT        NOT NULL DEFAULT 'Pengguna',
  email              TEXT        NOT NULL,
  phone              TEXT,
  category           TEXT        NOT NULL DEFAULT 'Pertanyaan Umum',
  subject            TEXT        NOT NULL DEFAULT 'Bantuan Layanan',
  message            TEXT,
  messages           JSONB       NOT NULL DEFAULT '[]',
  status             TEXT        NOT NULL DEFAULT 'Terbuka',
  admin_reply        TEXT,
  ip_address         TEXT,
  user_agent         TEXT,
  visitor_device_id  TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_support_tickets_user_id ON public.support_tickets (user_id);
CREATE INDEX idx_support_tickets_status  ON public.support_tickets (status);
CREATE INDEX idx_support_tickets_code    ON public.support_tickets (ticket_code);


-- ============================================================
-- BAGIAN 2: TRIGGERS
-- ============================================================

-- ------------------------------------------------------------
-- 2a. Auto-buat profil di public.users setiap kali ada user
--     baru yang sign up melalui Supabase Auth (signUp).
--     Membaca name, phone, role dari user_metadata.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users (id, name, email, phone, role)
  VALUES (
    NEW.id,
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'name', ''), split_part(NEW.email, '@', 1)),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'phone', ''),
    COALESCE(NEW.raw_user_meta_data->>'role',  'customer')
  )
  ON CONFLICT (id) DO UPDATE
    SET email      = EXCLUDED.email,
        name       = CASE WHEN EXCLUDED.name <> '' THEN EXCLUDED.name ELSE public.users.name END,
        updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ------------------------------------------------------------
-- 2b. Auto-update kolom updated_at di public.users
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();



-- ============================================================
-- BAGIAN 2.5: RLS HELPER FUNCTIONS
-- ============================================================
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin'
  );
$$;

CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS text
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT role FROM public.users WHERE id = auth.uid();
$$;

-- ============================================================
-- BAGIAN 3: ROW LEVEL SECURITY (RLS)
-- ============================================================

ALTER TABLE public.users          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_logs      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_chats    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;

-- ── USERS ────────────────────────────────────────────────────

-- User bisa baca profil sendiri
CREATE POLICY "users: baca profil sendiri"
  ON public.users FOR SELECT
  USING (auth.uid() = id);

-- User bisa update profil sendiri (tidak bisa ubah role sendiri)
CREATE POLICY "users: update profil sendiri"
  ON public.users FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- Admin bisa baca semua user
CREATE POLICY "users: admin baca semua"
  ON public.users FOR SELECT
  USING (public.is_admin());

-- Admin bisa update semua user (termasuk ubah role)
CREATE POLICY "users: admin update semua"
  ON public.users FOR UPDATE
  USING (public.is_admin());

-- Trigger INSERT diizinkan (service role)
CREATE POLICY "users: trigger insert"
  ON public.users FOR INSERT WITH CHECK (true);

-- ── STORES ───────────────────────────────────────────────────

-- Semua orang bisa lihat toko yang approved
-- Seller bisa lihat toko miliknya sendiri walau pending/rejected
-- Admin bisa lihat semua
CREATE POLICY "stores: lihat toko"
  ON public.stores FOR SELECT
  USING (
    status = 'approved'
    OR auth.uid() = user_id
    OR public.is_admin()
  );

-- User login bisa daftar toko baru
CREATE POLICY "stores: daftar toko baru"
  ON public.stores FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL AND auth.uid() = user_id);

-- Seller bisa update toko miliknya
CREATE POLICY "stores: seller update toko sendiri"
  ON public.stores FOR UPDATE
  USING (auth.uid() = user_id);

-- Admin bisa semua operasi
CREATE POLICY "stores: admin full access"
  ON public.stores FOR ALL
  USING (public.is_admin());

-- ── PRODUCTS ─────────────────────────────────────────────────

-- Semua orang (termasuk tidak login) bisa lihat produk
CREATE POLICY "products: lihat semua produk"
  ON public.products FOR SELECT USING (true);

-- Seller hanya bisa CRUD produk di toko miliknya
CREATE POLICY "products: seller kelola produk sendiri"
  ON public.products FOR ALL
  USING (EXISTS (
    SELECT 1 FROM public.stores s
    WHERE s.id = store_id AND s.user_id = auth.uid()
  ));

-- Admin bisa semua
CREATE POLICY "products: admin full access"
  ON public.products FOR ALL
  USING (public.is_admin());

-- ── ORDERS ───────────────────────────────────────────────────

-- Pembeli bisa lihat pesanan miliknya sendiri
CREATE POLICY "orders: lihat pesanan sendiri"
  ON public.orders FOR SELECT
  USING (auth.uid() = user_id);

-- Penjual bisa lihat pesanan yang masuk ke tokonya
CREATE POLICY "orders: seller lihat pesanan masuk"
  ON public.orders FOR SELECT
  USING (auth.uid() = seller_id);

-- Penjual bisa update status pesanan yang masuk ke tokonya
-- (mis. tandai "Pesanan Dikirim")
CREATE POLICY "orders: seller update pesanan masuk"
  ON public.orders FOR UPDATE
  USING (auth.uid() = seller_id);

-- User login bisa buat pesanan
CREATE POLICY "orders: buat pesanan"
  ON public.orders FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Pembeli bisa update pesanan miliknya sendiri (mis. konfirmasi diterima)
CREATE POLICY "orders: buyer update pesanan sendiri"
  ON public.orders FOR UPDATE
  USING (auth.uid() = user_id);

-- Admin bisa semua
CREATE POLICY "orders: admin full access"
  ON public.orders FOR ALL
  USING (public.is_admin());

-- ── USER_LOGS ────────────────────────────────────────────────

-- Siapa saja (termasuk anon) bisa insert log (untuk page views)
CREATE POLICY "user_logs: insert log"
  ON public.user_logs FOR INSERT WITH CHECK (true);

-- User bisa baca log dirinya sendiri
CREATE POLICY "user_logs: baca log sendiri"
  ON public.user_logs FOR SELECT
  USING (auth.uid() = user_id);

-- Admin bisa baca semua log
CREATE POLICY "user_logs: admin baca semua"
  ON public.user_logs FOR SELECT
  USING (public.is_admin());

-- ── ORDER_CHATS ──────────────────────────────────────────────
-- Buyer, seller pesanan terkait, dan admin bisa baca & kirim pesan

CREATE POLICY "order_chats: akses pihak terkait pesanan"
  ON public.order_chats FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_id AND (o.user_id = auth.uid() OR o.seller_id = auth.uid())
    )
    OR public.is_admin()
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_id AND (o.user_id = auth.uid() OR o.seller_id = auth.uid())
    )
    OR public.is_admin()
  );

-- ── SUPPORT_TICKETS ──────────────────────────────────────────

-- Siapa saja (termasuk tamu/anon) bisa membuat tiket
CREATE POLICY "support_tickets: buat tiket"
  ON public.support_tickets FOR INSERT WITH CHECK (true);

-- Tiket tamu (user_id kosong, dilacak lewat kode tiket di sisi klien)
-- bisa dibaca publik; tiket milik user login hanya bisa dibaca
-- pemiliknya sendiri; admin bisa baca semua.
CREATE POLICY "support_tickets: baca tiket"
  ON public.support_tickets FOR SELECT
  USING (
    user_id IS NULL
    OR auth.uid() = user_id
    OR public.is_admin()
  );

-- Hanya admin yang bisa update status/balasan tiket
CREATE POLICY "support_tickets: admin update"
  ON public.support_tickets FOR UPDATE
  USING (public.is_admin());


-- ============================================================
-- BAGIAN 4: REALTIME
-- ============================================================

ALTER PUBLICATION supabase_realtime ADD TABLE public.stores;
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.user_logs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.order_chats;
ALTER PUBLICATION supabase_realtime ADD TABLE public.support_tickets;


-- ============================================================
-- BAGIAN 5: SEED DATA DEMO
-- ============================================================
-- PENTING: Buat dulu user via Supabase Dashboard:
--   Authentication → Users → Add User:
--     1. admin@jaringlokal.com    | password: Admin@123
--     2. bambang@jaringlokal.com  | password: Seller@123
--     3. siti@jaringlokal.com     | password: Seller@123
--
-- Trigger handle_new_user() akan otomatis insert ke public.users.
-- Setelah user dibuat, jalankan blok SQL di bawah ini.
-- ============================================================

-- Set role & nama untuk user demo (aman diulang)
UPDATE public.users SET role = 'admin',  name = 'Admin JaringLokal'
  WHERE email = 'admin@jaringlokal.com';

UPDATE public.users SET role = 'seller', name = 'Pak Bambang Nelayan'
  WHERE email = 'bambang@jaringlokal.com';

UPDATE public.users SET role = 'seller', name = 'Ibu Siti Olahan Laut'
  WHERE email = 'siti@jaringlokal.com';

-- ------------------------------------------------------------
-- Seed Stores — minimal 5 toko nelayan/UMKM agar katalog
-- terlihat lengkap saat dinilai juri. Memakai WHERE NOT EXISTS
-- supaya aman dijalankan berkali-kali (tidak duplikat).
-- ------------------------------------------------------------
INSERT INTO public.stores (user_id, store_name, description, address, phone, status)
SELECT u.id, 'Toko Nelayan Bahari Pak Bambang',
  'Penyedia hasil laut segar langsung dari tangkapan nelayan pesisir Tuban.',
  'Jl. Pesisir Pantai Kradenan No. 12, Tuban', '081234567890', 'approved'
FROM public.users u WHERE u.email = 'bambang@jaringlokal.com'
AND NOT EXISTS (SELECT 1 FROM public.stores WHERE store_name = 'Toko Nelayan Bahari Pak Bambang');

INSERT INTO public.stores (user_id, store_name, description, address, phone, status)
SELECT u.id, 'Dapur Olahan Laut Ibu Siti',
  'Olahan khas ikan asap, terasi super, dan bandeng presto higienis.',
  'Jl. Raya Nelayan No. 45, Tuban', '089876543210', 'approved'
FROM public.users u WHERE u.email = 'siti@jaringlokal.com'
AND NOT EXISTS (SELECT 1 FROM public.stores WHERE store_name = 'Dapur Olahan Laut Ibu Siti');

-- 3 toko tambahan (tanpa akun login penjual, hanya untuk demo katalog)
-- agar total minimal 5 toko nelayan tampil di aplikasi
INSERT INTO public.stores (user_id, store_name, description, address, phone, status)
SELECT * FROM (VALUES
  (NULL::UUID, 'Toko Ikan Segar Pak Joko', 'Menjual aneka ikan laut segar hasil tangkapan harian nelayan Tuban.', 'Jl. Pantai Boom No. 8, Tuban', '081298765432', 'approved'),
  (NULL::UUID, 'UMKM Kerupuk & Ikan Asin Bu Ratna', 'Produsen kerupuk ikan dan ikan asin khas pesisir Tuban, higienis dan tanpa pengawet.', 'Jl. Kembang Bilo No. 21, Tuban', '082112345678', 'approved'),
  (NULL::UUID, 'Mina Bahari Pak Slamet', 'Kelompok nelayan muda penyedia hasil laut premium: kepiting, lobster, dan kerang.', 'Jl. Glondonggede, Tuban', '085734567890', 'approved'),
  (NULL::UUID, 'Kios Hasil Laut Berkah', 'Penyedia ikan dan kerang segar harian langsung dari nelayan sekitar.', 'Jl. Sunan Bonang No. 9, Tuban', '081399887766', 'approved')
) AS v(user_id, store_name, description, address, phone, status)
WHERE NOT EXISTS (SELECT 1 FROM public.stores WHERE store_name = v.store_name);

-- ------------------------------------------------------------
-- Seed Products — minimal 5 produk (di sini total 17 produk
-- tersebar di 5 toko). NOT EXISTS mengecek pasangan
-- (store_name, name) supaya tidak ada produk ganda saat diulang.
-- ------------------------------------------------------------
INSERT INTO public.products (store_id, store_name, name, price, category, stock, image, unit)
SELECT s.id, s.store_name, p.name, p.price::numeric, p.category, p.stock::int, p.image, p.unit
FROM (VALUES
  ('Toko Nelayan Bahari Pak Bambang', 'Rajungan Segar',     85000,  'Tangkapan Segar', 20, 'https://images.unsplash.com/photo-1599839619722-39751411ea63?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Toko Nelayan Bahari Pak Bambang', 'Cumi-cumi Segar',    60000,  'Tangkapan Segar', 40, 'https://images.unsplash.com/photo-1559868725-b467ec6a6d0c?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Toko Nelayan Bahari Pak Bambang', 'Udang Vaname Segar', 75000,  'Tangkapan Segar', 35, 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Toko Nelayan Bahari Pak Bambang', 'Ikan Kerapu Merah',  120000, 'Tangkapan Segar',  8, 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Toko Nelayan Bahari Pak Bambang', 'Kerang Hijau',       30000,  'Tangkapan Segar', 60, 'https://images.unsplash.com/photo-1569385210018-127685f22b5a?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Dapur Olahan Laut Ibu Siti',      'Terasi Pesisir Tuban', 25000, 'Olahan',         50, 'https://images.unsplash.com/photo-1621317762692-0f04f2f53472?auto=format&fit=crop&q=80&w=400', 'bungkus'),
  ('Dapur Olahan Laut Ibu Siti',      'Ikan Asap Tuban',    35000,  'Olahan',          30, 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Dapur Olahan Laut Ibu Siti',      'Bandeng Presto',     45000,  'Olahan',          25, 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&q=80&w=400', 'ekor'),
  ('Toko Ikan Segar Pak Joko', 'Ikan Tongkol Segar',   40000, 'Tangkapan Segar', 45, 'https://images.unsplash.com/photo-1595475207225-428b62bda831?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Toko Ikan Segar Pak Joko', 'Ikan Tenggiri Segar',  70000, 'Tangkapan Segar', 25, 'https://images.unsplash.com/photo-1580554530778-ca36943938b2?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Toko Ikan Segar Pak Joko', 'Ikan Layur Segar',     55000, 'Tangkapan Segar', 18, 'https://images.unsplash.com/photo-1524704796725-9fc3044a58b2?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('UMKM Kerupuk & Ikan Asin Bu Ratna', 'Kerupuk Ikan Tenggiri', 20000, 'Olahan', 70, 'https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&q=80&w=400', 'bungkus'),
  ('UMKM Kerupuk & Ikan Asin Bu Ratna', 'Ikan Asin Jambal',      32000, 'Olahan', 40, 'https://images.unsplash.com/photo-1611171711791-b872b6a9d61d?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('UMKM Kerupuk & Ikan Asin Bu Ratna', 'Petis Udang Khas Tuban',18000, 'Olahan', 55, 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&q=80&w=400', 'botol'),
  ('Mina Bahari Pak Slamet', 'Kepiting Bakau Segar',   95000,  'Tangkapan Segar', 15, 'https://images.unsplash.com/photo-1550747545-c896b5f89ff7?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Mina Bahari Pak Slamet', 'Lobster Air Laut',        180000, 'Tangkapan Segar', 10, 'https://images.unsplash.com/photo-1553247407-23251ce81f30?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Mina Bahari Pak Slamet', 'Kerang Dara Segar',       28000,  'Tangkapan Segar', 50, 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Kios Hasil Laut Berkah', 'Ikan Baronang Segar', 65000, 'Tangkapan Segar', 15, 'https://images.unsplash.com/photo-1517409217646-b816ba7dce95?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Kios Hasil Laut Berkah', 'Cumi Jarum', 45000, 'Tangkapan Segar', 30, 'https://images.unsplash.com/photo-1559868725-b467ec6a6d0c?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Dapur Olahan Laut Ibu Siti', 'Kepiting Soka Krispi', 55000, 'Olahan', 40, 'https://images.unsplash.com/photo-1569385210018-127685f22b5a?auto=format&fit=crop&q=80&w=400', 'bungkus'),
  ('Dapur Olahan Laut Ibu Siti', 'Terasi Udang Rebon', 28000, 'Olahan', 60, 'https://images.unsplash.com/photo-1621317762692-0f04f2f53472?auto=format&fit=crop&q=80&w=400', 'bungkus'),
  ('Mina Bahari Pak Slamet', 'Udang Ronggeng', 120000, 'Tangkapan Segar', 25, 'https://images.unsplash.com/photo-1553247407-23251ce81f30?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Kios Hasil Laut Berkah', 'Ikan Kerapu Hitam', 105000, 'Tangkapan Segar', 10, 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('UMKM Kerupuk & Ikan Asin Bu Ratna', 'Kerupuk Kulit Ikan', 22000, 'Olahan', 80, 'https://images.unsplash.com/photo-1600628421055-4d30de868b8f?auto=format&fit=crop&q=80&w=400', 'bungkus')
) AS p(store_name, name, price, category, stock, image, unit)
JOIN public.stores s ON s.store_name = p.store_name
WHERE NOT EXISTS (
  SELECT 1 FROM public.products pr WHERE pr.store_name = p.store_name AND pr.name = p.name
);

-- ------------------------------------------------------------
-- Seed Orders (contoh histori transaksi) — dicek lewat items
-- supaya tidak dobel kalau file ini dijalankan ulang. Kolom
-- seller_id/store_id diisi otomatis dari nama toko agar pesanan
-- ini muncul di dashboard penjual terkait.
-- ------------------------------------------------------------
INSERT INTO public.orders (user_name, seller_id, store_id, store_name, total_amount, status, escrow_status, items, created_at)
SELECT v.user_name, s.user_id, s.id, v.store_name, v.total_amount, v.status, v.escrow_status, v.items, v.created_at
FROM (VALUES
  ('Budi Santoso', 'Toko Nelayan Bahari Pak Bambang', 255000, 'Selesai', 'completed',
   '[{"id":1,"name":"Rajungan Segar","price":85000,"quantity":3,"unit":"kg","store_name":"Toko Nelayan Bahari Pak Bambang"}]'::jsonb,
   '2026-08-01T10:00:00+07:00'::timestamptz),
  ('Siti Rahma', 'Dapur Olahan Laut Ibu Siti', 125000, 'Selesai', 'completed',
   '[{"id":6,"name":"Terasi Pesisir Tuban","price":25000,"quantity":5,"unit":"bungkus","store_name":"Dapur Olahan Laut Ibu Siti"}]'::jsonb,
   '2026-08-03T14:30:00+07:00'::timestamptz),
  ('Ahmad Fauzi', 'Toko Nelayan Bahari Pak Bambang', 180000, 'Pesanan Dikirim', 'shipped',
   '[{"id":2,"name":"Cumi-cumi Segar","price":60000,"quantity":3,"unit":"kg","store_name":"Toko Nelayan Bahari Pak Bambang"}]'::jsonb,
   '2026-08-05T09:15:00+07:00'::timestamptz),
  ('Dewi Lestari', 'Dapur Olahan Laut Ibu Siti', 105000, 'Dana Ditahan di Escrow Admin', 'in_escrow',
   '[{"id":7,"name":"Ikan Asap Tuban","price":35000,"quantity":3,"unit":"kg","store_name":"Dapur Olahan Laut Ibu Siti"}]'::jsonb,
   '2026-08-06T16:20:00+07:00'::timestamptz),
  ('Rudi Hartono', 'Toko Nelayan Bahari Pak Bambang', 600000, 'Menunggu Pembayaran Escrow', 'pending_payment',
   '[{"id":4,"name":"Ikan Kerapu Merah","price":120000,"quantity":5,"unit":"kg","store_name":"Toko Nelayan Bahari Pak Bambang"}]'::jsonb,
   '2026-08-10T08:00:00+07:00'::timestamptz)
) AS v(user_name, store_name, total_amount, status, escrow_status, items, created_at)
JOIN public.stores s ON s.store_name = v.store_name
WHERE NOT EXISTS (
  SELECT 1 FROM public.orders o WHERE o.user_name = v.user_name AND o.total_amount = v.total_amount AND o.created_at = v.created_at
);

-- ------------------------------------------------------------
-- Seed User Activity Logs (contoh log demo)
-- ------------------------------------------------------------
INSERT INTO public.user_logs (user_name, action, ip_address, city, region, country, device_type, created_at)
SELECT * FROM (VALUES
  ('Budi Santoso',  'login',    '180.252.124.58', 'Tuban',    'Jawa Timur', 'Indonesia', 'Mobile',  '2026-08-01T10:00:00+07:00'::timestamptz),
  ('Budi Santoso',  'purchase', '180.252.124.58', 'Tuban',    'Jawa Timur', 'Indonesia', 'Mobile',  '2026-08-01T10:05:00+07:00'::timestamptz),
  ('Siti Rahma',    'register', '114.125.45.12',  'Surabaya', 'Jawa Timur', 'Indonesia', 'Mobile',  '2026-08-03T14:20:00+07:00'::timestamptz),
  ('Siti Rahma',    'login',    '114.125.45.12',  'Surabaya', 'Jawa Timur', 'Indonesia', 'Mobile',  '2026-08-03T14:25:00+07:00'::timestamptz),
  ('Ahmad Fauzi',   'login',    '125.164.88.90',  'Lamongan', 'Jawa Timur', 'Indonesia', 'Desktop', '2026-08-05T09:10:00+07:00'::timestamptz),
  ('Ahmad Fauzi',   'purchase', '125.164.88.90',  'Lamongan', 'Jawa Timur', 'Indonesia', 'Desktop', '2026-08-05T09:15:00+07:00'::timestamptz),
  ('Dewi Lestari',  'login',    '180.244.15.22',  'Gresik',   'Jawa Timur', 'Indonesia', 'Mobile',  '2026-08-06T16:15:00+07:00'::timestamptz),
  ('Rudi Hartono',  'register', '36.82.191.44',   'Bojonegoro','Jawa Timur','Indonesia', 'Desktop', '2026-08-10T07:55:00+07:00'::timestamptz),
  ('Rudi Hartono',  'purchase', '36.82.191.44',   'Bojonegoro','Jawa Timur','Indonesia', 'Desktop', '2026-08-10T08:00:00+07:00'::timestamptz),
  ('Pengunjung',    'page_view','103.47.12.88',   'Malang',   'Jawa Timur', 'Indonesia', 'Mobile',  '2026-08-11T13:30:00+07:00'::timestamptz)
) AS v(user_name, action, ip_address, city, region, country, device_type, created_at)
WHERE NOT EXISTS (
  SELECT 1 FROM public.user_logs l WHERE l.user_name = v.user_name AND l.action = v.action AND l.created_at = v.created_at
);

-- ============================================================
-- SELESAI — Verifikasi:
--   SELECT * FROM public.users;
--   SELECT * FROM public.stores;
--   SELECT * FROM public.products;
--   SELECT * FROM public.orders;
--   SELECT * FROM public.user_logs;
-- ============================================================


-- ============================================================
-- BAGIAN 6: MIGRASI UNTUK DATABASE YANG SUDAH LIVE
-- ============================================================
-- INI YANG PERLU DIJALANKAN DI PROJECT SUPABASE KAMU SEKARANG.
-- Aman dijalankan berkali-kali (idempotent) — tidak akan error
-- "already exists" dan tidak menghapus data yang sudah ada.
-- ============================================================

-- ── 6.1 Kolom baru di tabel orders (escrow, seller, toko) ────
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS seller_id     UUID REFERENCES public.users(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS store_id      BIGINT REFERENCES public.stores(id) ON DELETE SET NULL;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS store_name    TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS shipping_fee  NUMERIC NOT NULL DEFAULT 0;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS escrow_status TEXT NOT NULL DEFAULT 'pending_payment';
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_orders_seller_id ON public.orders (seller_id);
CREATE INDEX IF NOT EXISTS idx_orders_store_id  ON public.orders (store_id);

-- Isi seller_id/store_name pada pesanan lama yang mungkin sudah ada,
-- dicocokkan lewat nama toko yang tersimpan di kolom items (JSONB)
UPDATE public.orders o
SET seller_id  = COALESCE(o.seller_id, s.user_id),
    store_id   = COALESCE(o.store_id, s.id),
    store_name = COALESCE(o.store_name, s.store_name)
FROM public.stores s
WHERE o.store_name IS NULL
  AND o.items IS NOT NULL
  AND jsonb_array_length(o.items) > 0
  AND s.store_name = (o.items->0->>'store_name');

-- ── 6.2 Tabel order_chats (ruang chat 3 pihak per pesanan) ───
CREATE TABLE IF NOT EXISTS public.order_chats (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id    BIGINT      NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  sender_id   UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  sender_name TEXT        NOT NULL DEFAULT 'Pengguna',
  sender_role TEXT        NOT NULL DEFAULT 'buyer',
  text        TEXT        NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_order_chats_order_id ON public.order_chats (order_id);
ALTER TABLE public.order_chats ENABLE ROW LEVEL SECURITY;

-- ── 6.3 Tabel support_tickets (tiket dukungan) ───────────────
CREATE TABLE IF NOT EXISTS public.support_tickets (
  id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_code        TEXT        NOT NULL UNIQUE,
  user_id            UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  name               TEXT        NOT NULL DEFAULT 'Pengguna',
  email              TEXT        NOT NULL,
  phone              TEXT,
  category           TEXT        NOT NULL DEFAULT 'Pertanyaan Umum',
  subject            TEXT        NOT NULL DEFAULT 'Bantuan Layanan',
  message            TEXT,
  messages           JSONB       NOT NULL DEFAULT '[]',
  status             TEXT        NOT NULL DEFAULT 'Terbuka',
  admin_reply        TEXT,
  ip_address         TEXT,
  user_agent         TEXT,
  visitor_device_id  TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_support_tickets_user_id ON public.support_tickets (user_id);
CREATE INDEX IF NOT EXISTS idx_support_tickets_status  ON public.support_tickets (status);
CREATE INDEX IF NOT EXISTS idx_support_tickets_code    ON public.support_tickets (ticket_code);
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;

-- ── 6.4 RLS helper functions (kalau belum ada) ───────────────
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN LANGUAGE sql SECURITY DEFINER AS $$
  SELECT EXISTS (SELECT 1 FROM public.users WHERE id = auth.uid() AND role = 'admin');
$$;

-- ── 6.5 Perbaikan & tambahan RLS policy untuk orders ─────────
-- Hapus dulu kalau sudah ada (supaya aman diulang), lalu buat ulang
DROP POLICY IF EXISTS "orders: lihat pesanan sendiri"       ON public.orders;
DROP POLICY IF EXISTS "orders: seller lihat pesanan masuk"  ON public.orders;
DROP POLICY IF EXISTS "orders: seller update pesanan masuk" ON public.orders;
DROP POLICY IF EXISTS "orders: buat pesanan"                ON public.orders;
DROP POLICY IF EXISTS "orders: buyer update pesanan sendiri" ON public.orders;
DROP POLICY IF EXISTS "orders: admin full access"           ON public.orders;

CREATE POLICY "orders: lihat pesanan sendiri"
  ON public.orders FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "orders: seller lihat pesanan masuk"
  ON public.orders FOR SELECT USING (auth.uid() = seller_id);

CREATE POLICY "orders: seller update pesanan masuk"
  ON public.orders FOR UPDATE USING (auth.uid() = seller_id);

CREATE POLICY "orders: buat pesanan"
  ON public.orders FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "orders: buyer update pesanan sendiri"
  ON public.orders FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "orders: admin full access"
  ON public.orders FOR ALL USING (public.is_admin());

-- ── 6.6 RLS policy untuk order_chats ──────────────────────────
DROP POLICY IF EXISTS "order_chats: akses pihak terkait pesanan" ON public.order_chats;

CREATE POLICY "order_chats: akses pihak terkait pesanan"
  ON public.order_chats FOR ALL
  USING (
    EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_id AND (o.user_id = auth.uid() OR o.seller_id = auth.uid()))
    OR public.is_admin()
  )
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.orders o WHERE o.id = order_id AND (o.user_id = auth.uid() OR o.seller_id = auth.uid()))
    OR public.is_admin()
  );

-- ── 6.7 RLS policy untuk support_tickets ──────────────────────
DROP POLICY IF EXISTS "support_tickets: buat tiket"  ON public.support_tickets;
DROP POLICY IF EXISTS "support_tickets: baca tiket"  ON public.support_tickets;
DROP POLICY IF EXISTS "support_tickets: admin update" ON public.support_tickets;

CREATE POLICY "support_tickets: buat tiket"
  ON public.support_tickets FOR INSERT WITH CHECK (true);

CREATE POLICY "support_tickets: baca tiket"
  ON public.support_tickets FOR SELECT
  USING (user_id IS NULL OR auth.uid() = user_id OR public.is_admin());

CREATE POLICY "support_tickets: admin update"
  ON public.support_tickets FOR UPDATE USING (public.is_admin());

-- ── 6.8 Aktifkan realtime untuk tabel baru ───────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'order_chats'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.order_chats;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = 'support_tickets'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.support_tickets;
  END IF;
END $$;

-- ============================================================
-- SELESAI BAGIAN 6 — Verifikasi:
--   SELECT column_name FROM information_schema.columns WHERE table_name = 'orders';
--   SELECT tablename FROM pg_tables WHERE schemaname = 'public';
--   SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public' ORDER BY tablename;
-- ============================================================
