-- ============================================================
-- JaringLokal (AerLaut) — Fresh Database Schema
-- Supabase Auth Edition (Password hashing bcrypt otomatis)
-- ============================================================
-- Jalankan SATU KALI di project Supabase baru:
-- https://supabase.com/dashboard/project/[YOUR_PROJECT]/sql/new
-- ============================================================

-- ============================================================
-- BAGIAN 1: TABEL-TABEL UTAMA
-- ============================================================

-- ------------------------------------------------------------
-- 1a. public.users — Profile extension dari auth.users
--     id = UUID dari auth.users (bukan auto-increment)
--     TIDAK ada kolom password — dikelola Supabase Auth (bcrypt)
-- ------------------------------------------------------------
CREATE TABLE public.users (
  id         UUID        PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name       TEXT        NOT NULL DEFAULT '',
  email      TEXT        NOT NULL UNIQUE,
  phone      TEXT        NOT NULL DEFAULT '',
  role       TEXT        NOT NULL DEFAULT 'customer'
               CHECK (role IN ('customer', 'seller', 'admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_email ON public.users (email);
CREATE INDEX idx_users_role  ON public.users (role);
CREATE INDEX idx_users_phone ON public.users (phone);

-- ------------------------------------------------------------
-- 1b. public.stores — Toko Penjual
-- ------------------------------------------------------------
CREATE TABLE public.stores (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID        REFERENCES public.users(id) ON DELETE CASCADE,
  store_name  TEXT        NOT NULL,
  description TEXT,
  address     TEXT,
  phone       TEXT,
  status      TEXT        NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'approved', 'rejected')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_stores_user_id ON public.stores (user_id);
CREATE INDEX idx_stores_status  ON public.stores (status);

-- ------------------------------------------------------------
-- 1c. public.products — Katalog Produk
-- ------------------------------------------------------------
CREATE TABLE public.products (
  id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id   BIGINT      REFERENCES public.stores(id) ON DELETE SET NULL,
  store_name TEXT        NOT NULL DEFAULT 'Toko Nelayan',
  name       TEXT        NOT NULL,
  price      NUMERIC     NOT NULL CHECK (price >= 0),
  category   TEXT        NOT NULL,
  stock      INT         NOT NULL DEFAULT 0 CHECK (stock >= 0),
  image      TEXT,
  unit       TEXT        NOT NULL DEFAULT 'kg',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_products_store_id ON public.products (store_id);
CREATE INDEX idx_products_category ON public.products (category);

-- ------------------------------------------------------------
-- 1d. public.orders — Pesanan Pelanggan
-- ------------------------------------------------------------
CREATE TABLE public.orders (
  id           BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id      UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  user_name    TEXT        NOT NULL DEFAULT 'Pelanggan',
  total_amount NUMERIC     NOT NULL CHECK (total_amount >= 0),
  status       TEXT        NOT NULL DEFAULT 'Menunggu Konfirmasi',
  items        JSONB       NOT NULL DEFAULT '[]',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_orders_user_id   ON public.orders (user_id);
CREATE INDEX idx_orders_status    ON public.orders (status);
CREATE INDEX idx_orders_created   ON public.orders (created_at DESC);

-- ------------------------------------------------------------
-- 1e. public.user_logs — Log Aktivitas & Demografi Pengunjung
-- ------------------------------------------------------------
CREATE TABLE public.user_logs (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     UUID        REFERENCES public.users(id) ON DELETE SET NULL,
  user_name   TEXT        NOT NULL DEFAULT 'Pengunjung',
  action      TEXT        NOT NULL, -- 'login' | 'register' | 'purchase' | 'page_view'
  ip_address  TEXT,
  city        TEXT,
  region      TEXT,
  country     TEXT,
  device_type TEXT,                 -- 'Mobile' | 'Desktop' | 'Tablet'
  metadata    JSONB       NOT NULL DEFAULT '{}',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_user_logs_user_id    ON public.user_logs (user_id);
CREATE INDEX idx_user_logs_action     ON public.user_logs (action);
CREATE INDEX idx_user_logs_created_at ON public.user_logs (created_at DESC);


-- ============================================================
-- BAGIAN 2: TRIGGERS
-- ============================================================

-- ------------------------------------------------------------
-- 2a. Auto-buat profil di public.users setiap kali ada user
--     baru yang sign up melalui Supabase Auth (signUp).
--     Membaca name, phone, role dari user_metadata.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users (id, name, email, phone, role)
  VALUES (
    NEW.id,
    COALESCE(NULLIF(NEW.raw_user_meta_data->>'name', ''), split_part(NEW.email, '@', 1)),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'phone', ''),
    COALESCE(NEW.raw_user_meta_data->>'role',  'customer')
  )
  ON CONFLICT (id) DO UPDATE
    SET email      = EXCLUDED.email,
        name       = CASE WHEN EXCLUDED.name <> '' THEN EXCLUDED.name ELSE public.users.name END,
        updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ------------------------------------------------------------
-- 2b. Auto-update kolom updated_at di public.users
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER users_updated_at
  BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- ============================================================
-- BAGIAN 3: ROW LEVEL SECURITY (RLS)
-- ============================================================

ALTER TABLE public.users      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_logs  ENABLE ROW LEVEL SECURITY;

-- ── USERS ────────────────────────────────────────────────────

-- User bisa baca profil sendiri
CREATE POLICY "users: baca profil sendiri"
  ON public.users FOR SELECT
  USING (auth.uid() = id);

-- User bisa update profil sendiri (tidak bisa ubah role sendiri)
CREATE POLICY "users: update profil sendiri"
  ON public.users FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (
    auth.uid() = id
    AND role = (SELECT role FROM public.users WHERE id = auth.uid())
  );

-- Admin bisa baca semua user
CREATE POLICY "users: admin baca semua"
  ON public.users FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin'
  ));

-- Admin bisa update semua user (termasuk ubah role)
CREATE POLICY "users: admin update semua"
  ON public.users FOR UPDATE
  USING (EXISTS (
    SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin'
  ));

-- Trigger INSERT diizinkan (service role)
CREATE POLICY "users: trigger insert"
  ON public.users FOR INSERT WITH CHECK (true);

-- ── STORES ───────────────────────────────────────────────────

-- Semua orang bisa lihat toko yang approved
-- Seller bisa lihat toko miliknya sendiri walau pending/rejected
-- Admin bisa lihat semua
CREATE POLICY "stores: lihat toko"
  ON public.stores FOR SELECT
  USING (
    status = 'approved'
    OR auth.uid() = user_id
    OR EXISTS (SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin')
  );

-- User login bisa daftar toko baru
CREATE POLICY "stores: daftar toko baru"
  ON public.stores FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL AND auth.uid() = user_id);

-- Seller bisa update toko miliknya
CREATE POLICY "stores: seller update toko sendiri"
  ON public.stores FOR UPDATE
  USING (auth.uid() = user_id);

-- Admin bisa semua operasi
CREATE POLICY "stores: admin full access"
  ON public.stores FOR ALL
  USING (EXISTS (
    SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin'
  ));

-- ── PRODUCTS ─────────────────────────────────────────────────

-- Semua orang (termasuk tidak login) bisa lihat produk
CREATE POLICY "products: lihat semua produk"
  ON public.products FOR SELECT USING (true);

-- Seller hanya bisa CRUD produk di toko miliknya
CREATE POLICY "products: seller kelola produk sendiri"
  ON public.products FOR ALL
  USING (EXISTS (
    SELECT 1 FROM public.stores s
    WHERE s.id = store_id AND s.user_id = auth.uid()
  ));

-- Admin bisa semua
CREATE POLICY "products: admin full access"
  ON public.products FOR ALL
  USING (EXISTS (
    SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin'
  ));

-- ── ORDERS ───────────────────────────────────────────────────

-- User bisa lihat pesanan sendiri
CREATE POLICY "orders: lihat pesanan sendiri"
  ON public.orders FOR SELECT
  USING (auth.uid() = user_id);

-- User login bisa buat pesanan
CREATE POLICY "orders: buat pesanan"
  ON public.orders FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Admin bisa semua
CREATE POLICY "orders: admin full access"
  ON public.orders FOR ALL
  USING (EXISTS (
    SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin'
  ));

-- ── USER_LOGS ────────────────────────────────────────────────

-- Siapa saja (termasuk anon) bisa insert log (untuk page views)
CREATE POLICY "user_logs: insert log"
  ON public.user_logs FOR INSERT WITH CHECK (true);

-- User bisa baca log dirinya sendiri
CREATE POLICY "user_logs: baca log sendiri"
  ON public.user_logs FOR SELECT
  USING (auth.uid() = user_id);

-- Admin bisa baca semua log
CREATE POLICY "user_logs: admin baca semua"
  ON public.user_logs FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.users u WHERE u.id = auth.uid() AND u.role = 'admin'
  ));


-- ============================================================
-- BAGIAN 4: REALTIME
-- ============================================================

ALTER PUBLICATION supabase_realtime ADD TABLE public.stores;
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.user_logs;


-- ============================================================
-- BAGIAN 5: SEED DATA DEMO
-- ============================================================
-- PENTING: Buat dulu user via Supabase Dashboard:
--   Authentication → Users → Add User:
--     1. admin@jaringlokal.com    | password: Admin@123
--     2. bambang@jaringlokal.com  | password: Seller@123
--     3. siti@jaringlokal.com     | password: Seller@123
--
-- Trigger handle_new_user() akan otomatis insert ke public.users.
-- Setelah user dibuat, jalankan blok SQL di bawah ini.
-- ============================================================

-- Set role & nama untuk user demo
UPDATE public.users SET role = 'admin',  name = 'Admin JaringLokal'
  WHERE email = 'admin@jaringlokal.com';

UPDATE public.users SET role = 'seller', name = 'Pak Bambang Nelayan'
  WHERE email = 'bambang@jaringlokal.com';

UPDATE public.users SET role = 'seller', name = 'Ibu Siti Olahan Laut'
  WHERE email = 'siti@jaringlokal.com';

-- Seed Stores
INSERT INTO public.stores (user_id, store_name, description, address, phone, status)
SELECT id, 'Toko Nelayan Bahari Pak Bambang',
  'Penyedia hasil laut segar langsung dari tangkapan nelayan pesisir Tuban.',
  'Jl. Pesisir Pantai Kradenan No. 12, Tuban', '081234567890', 'approved'
FROM public.users WHERE email = 'bambang@jaringlokal.com';

INSERT INTO public.stores (user_id, store_name, description, address, phone, status)
SELECT id, 'Dapur Olahan Laut Ibu Siti',
  'Olahan khas ikan asap, terasi super, dan bandeng presto higienis.',
  'Jl. Raya Nelayan No. 45, Tuban', '089876543210', 'approved'
FROM public.users WHERE email = 'siti@jaringlokal.com';

-- Seed Products (Otomatis skip jika toko belum ada)
INSERT INTO public.products (store_id, store_name, name, price, category, stock, image, unit)
SELECT s.id, s.store_name, p.name, p.price::numeric, p.category, p.stock::int, p.image, p.unit
FROM (VALUES
  ('Toko Nelayan Bahari Pak Bambang', 'Rajungan Segar',     85000,  'Tangkapan Segar', 20, 'https://images.unsplash.com/photo-1599839619722-39751411ea63?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Toko Nelayan Bahari Pak Bambang', 'Cumi-cumi Segar',    60000,  'Tangkapan Segar', 40, 'https://images.unsplash.com/photo-1559868725-b467ec6a6d0c?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Toko Nelayan Bahari Pak Bambang', 'Udang Vaname Segar', 75000,  'Tangkapan Segar', 35, 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Toko Nelayan Bahari Pak Bambang', 'Ikan Kerapu Merah',  120000, 'Tangkapan Segar',  8, 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Toko Nelayan Bahari Pak Bambang', 'Kerang Hijau',       30000,  'Tangkapan Segar', 60, 'https://images.unsplash.com/photo-1569385210018-127685f22b5a?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Dapur Olahan Laut Ibu Siti',      'Terasi Pesisir Tuban', 25000, 'Olahan',         50, 'https://images.unsplash.com/photo-1621317762692-0f04f2f53472?auto=format&fit=crop&q=80&w=400', 'bungkus'),
  ('Dapur Olahan Laut Ibu Siti',      'Ikan Asap Tuban',    35000,  'Olahan',          30, 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&q=80&w=400', 'kg'),
  ('Dapur Olahan Laut Ibu Siti',      'Bandeng Presto',     45000,  'Olahan',          25, 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&q=80&w=400', 'ekor')
) AS p(store_name, name, price, category, stock, image, unit)
JOIN public.stores s ON s.store_name = p.store_name;

-- Seed Orders (User ID bisa NULL untuk guest)
INSERT INTO public.orders (user_name, total_amount, status, items, created_at)
VALUES
  ('Budi Santoso', 255000, 'Selesai',
   '[{"id":1,"name":"Rajungan Segar","price":85000,"quantity":3,"unit":"kg","store_name":"Toko Nelayan Bahari Pak Bambang"}]',
   '2026-08-01T10:00:00+07:00'),
  ('Siti Rahma', 125000, 'Selesai',
   '[{"id":6,"name":"Terasi Pesisir Tuban","price":25000,"quantity":5,"unit":"bungkus","store_name":"Dapur Olahan Laut Ibu Siti"}]',
   '2026-08-03T14:30:00+07:00'),
  ('Ahmad Fauzi', 180000, 'Dikirim',
   '[{"id":2,"name":"Cumi-cumi Segar","price":60000,"quantity":3,"unit":"kg","store_name":"Toko Nelayan Bahari Pak Bambang"}]',
   '2026-08-05T09:15:00+07:00'),
  ('Dewi Lestari', 105000, 'Diproses',
   '[{"id":7,"name":"Ikan Asap Tuban","price":35000,"quantity":3,"unit":"kg","store_name":"Dapur Olahan Laut Ibu Siti"}]',
   '2026-08-06T16:20:00+07:00'),
  ('Rudi Hartono', 600000, 'Menunggu Konfirmasi',
   '[{"id":4,"name":"Ikan Kerapu Merah","price":120000,"quantity":5,"unit":"kg","store_name":"Toko Nelayan Bahari Pak Bambang"}]',
   '2026-08-10T08:00:00+07:00');

-- Seed User Activity Logs
INSERT INTO public.user_logs (user_name, action, ip_address, city, region, country, device_type, created_at)
VALUES
  ('Budi Santoso',  'login',    '180.252.124.58', 'Tuban',    'Jawa Timur', 'Indonesia', 'Mobile',  '2026-08-01T10:00:00+07:00'),
  ('Budi Santoso',  'purchase', '180.252.124.58', 'Tuban',    'Jawa Timur', 'Indonesia', 'Mobile',  '2026-08-01T10:05:00+07:00'),
  ('Siti Rahma',    'register', '114.125.45.12',  'Surabaya', 'Jawa Timur', 'Indonesia', 'Mobile',  '2026-08-03T14:20:00+07:00'),
  ('Siti Rahma',    'login',    '114.125.45.12',  'Surabaya', 'Jawa Timur', 'Indonesia', 'Mobile',  '2026-08-03T14:25:00+07:00'),
  ('Ahmad Fauzi',   'login',    '125.164.88.90',  'Lamongan', 'Jawa Timur', 'Indonesia', 'Desktop', '2026-08-05T09:10:00+07:00'),
  ('Ahmad Fauzi',   'purchase', '125.164.88.90',  'Lamongan', 'Jawa Timur', 'Indonesia', 'Desktop', '2026-08-05T09:15:00+07:00'),
  ('Dewi Lestari',  'login',    '180.244.15.22',  'Gresik',   'Jawa Timur', 'Indonesia', 'Mobile',  '2026-08-06T16:15:00+07:00'),
  ('Rudi Hartono',  'register', '36.82.191.44',   'Bojonegoro','Jawa Timur','Indonesia', 'Desktop', '2026-08-10T07:55:00+07:00'),
  ('Rudi Hartono',  'purchase', '36.82.191.44',   'Bojonegoro','Jawa Timur','Indonesia', 'Desktop', '2026-08-10T08:00:00+07:00'),
  ('Pengunjung',    'page_view','103.47.12.88',   'Malang',   'Jawa Timur', 'Indonesia', 'Mobile',  '2026-08-11T13:30:00+07:00');

-- ============================================================
-- SELESAI — Verifikasi:
--   SELECT * FROM public.users;
--   SELECT * FROM public.stores;
--   SELECT * FROM public.products;
--   SELECT * FROM public.orders;
--   SELECT * FROM public.user_logs;
-- ============================================================
