-- ============================================================
-- AerLaut (JaringLokal) Online Marketplace Database Schema
-- Robust & Safe SQL Script for Supabase PostgreSQL SQL Editor
-- ============================================================

-- ------------------------------------------------------------
-- STEP 1: CREATE ALL TABLES FIRST
-- ------------------------------------------------------------

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role TEXT DEFAULT 'customer',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure role column exists if users table was created previously
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'customer';

-- 2. Create Stores Table
CREATE TABLE IF NOT EXISTS public.stores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  store_name TEXT NOT NULL,
  description TEXT,
  address TEXT,
  phone TEXT,
  status TEXT DEFAULT 'approved',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT REFERENCES public.stores(id) ON DELETE SET NULL,
  store_name TEXT DEFAULT 'Toko Nelayan Bahari Pak Bambang',
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  category TEXT NOT NULL,
  stock INT DEFAULT 0,
  image TEXT,
  unit TEXT DEFAULT 'kg',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure store columns exist if products table was created previously
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS store_id BIGINT REFERENCES public.stores(id) ON DELETE SET NULL;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS store_name TEXT DEFAULT 'Toko Nelayan Bahari Pak Bambang';

-- 4. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL,
  total_amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'Menunggu Konfirmasi',
  items JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Create Support Tickets Table (SQL Support System)
CREATE TABLE IF NOT EXISTS public.support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  category TEXT NOT NULL DEFAULT 'Pertanyaan Umum',
  subject TEXT NOT NULL,
  message TEXT,
  messages JSONB DEFAULT '[]'::jsonb,
  status TEXT DEFAULT 'Terbuka', -- 'Terbuka', 'Sedang Diproses', 'Selesai', 'Tutup'
  admin_reply TEXT,
  ip_address TEXT,
  user_agent TEXT,
  visitor_device_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure IP, User Agent & Device ID columns exist if support_tickets table was created previously
ALTER TABLE public.support_tickets ADD COLUMN IF NOT EXISTS ip_address TEXT;
ALTER TABLE public.support_tickets ADD COLUMN IF NOT EXISTS user_agent TEXT;
ALTER TABLE public.support_tickets ADD COLUMN IF NOT EXISTS visitor_device_id TEXT;

-- SQL Auto-Update Query: Automatically close tickets with no activity/updates for 1 week (7 days)
-- UPDATE public.support_tickets 
-- SET status = 'Selesai', 
--     admin_reply = 'Otomasisasi Sistem: Tiket ditutup secara otomatis karena tidak ada aktivitas selama 1 minggu.',
--     updated_at = NOW() 
-- WHERE (status = 'Terbuka' OR status = 'Sedang Diproses') 
--   AND updated_at < NOW() - INTERVAL '7 days';

-- ------------------------------------------------------------
-- STEP 2: SEED INITIAL DATA
-- ------------------------------------------------------------

-- Seed Initial Users
INSERT INTO public.users (name, email, password, role)
VALUES 
  ('Admin JaringLokal', 'admin@jaringlokal.com', 'admin123', 'admin'),
  ('Pak Bambang Nelayan', 'bambang@jaringlokal.com', 'seller123', 'seller'),
  ('Ibu Siti Olahan Laut', 'siti@jaringlokal.com', 'seller123', 'seller')
ON CONFLICT (email) DO NOTHING;

-- Seed Initial Stores
INSERT INTO public.stores (id, user_id, store_name, description, address, phone, status)
VALUES
  (1, 2, 'Toko Nelayan Bahari Pak Bambang', 'Penyedia hasil laut segar langsung dari tangkapan nelayan pesisir Tuban.', 'Jl. Pesisir Pantai Kradenan No. 12, Tuban', '081234567890', 'approved'),
  (2, 3, 'Dapur Olahan Laut Ibu Siti', 'Olahan khas ikan asap, terasi super, dan bandeng presto higienis.', 'Jl. Raya Nelayan No. 45, Tuban', '089876543210', 'approved')
ON CONFLICT (id) DO NOTHING;

-- Seed Initial Products
INSERT INTO public.products (id, store_id, store_name, name, price, category, stock, image, unit) VALUES
(1, 2, 'Dapur Olahan Laut Ibu Siti', 'Terasi Pesisir Tuban', 25000, 'Olahan', 50, 'https://images.unsplash.com/photo-1621317762692-0f04f2f53472?auto=format&fit=crop&q=80&w=400', 'bungkus'),
(2, 1, 'Toko Nelayan Bahari Pak Bambang', 'Rajungan Segar', 85000, 'Tangkapan Segar', 20, 'https://images.unsplash.com/photo-1599839619722-39751411ea63?auto=format&fit=crop&q=80&w=400', 'kg'),
(3, 2, 'Dapur Olahan Laut Ibu Siti', 'Ikan Asap Tuban', 35000, 'Olahan', 30, 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&q=80&w=400', 'kg'),
(4, 1, 'Toko Nelayan Bahari Pak Bambang', 'Cumi-cumi Segar', 60000, 'Tangkapan Segar', 40, 'https://images.unsplash.com/photo-1559868725-b467ec6a6d0c?auto=format&fit=crop&q=80&w=400', 'kg'),
(5, 1, 'Toko Nelayan Bahari Pak Bambang', 'Udang Vaname Segar', 75000, 'Tangkapan Segar', 35, 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&q=80&w=400', 'kg'),
(6, 1, 'Toko Nelayan Bahari Pak Bambang', 'Ikan Kerapu Merah', 120000, 'Tangkapan Segar', 8, 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=400', 'kg'),
(7, 1, 'Toko Nelayan Bahari Pak Bambang', 'Kerang Hijau', 30000, 'Tangkapan Segar', 60, 'https://images.unsplash.com/photo-1569385210018-127685f22b5a?auto=format&fit=crop&q=80&w=400', 'kg'),
(8, 2, 'Dapur Olahan Laut Ibu Siti', 'Bandeng Presto', 45000, 'Olahan', 25, 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&q=80&w=400', 'ekor')
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------
-- STEP 3: ENABLE RLS & CREATE PUBLIC POLICIES
-- ------------------------------------------------------------

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public users access" ON public.users;
DROP POLICY IF EXISTS "Public stores access" ON public.stores;
DROP POLICY IF EXISTS "Public products access" ON public.products;
DROP POLICY IF EXISTS "Public orders access" ON public.orders;
DROP POLICY IF EXISTS "Public support_tickets access" ON public.support_tickets;

CREATE POLICY "Public users access" ON public.users FOR ALL USING (true);
CREATE POLICY "Public stores access" ON public.stores FOR ALL USING (true);
CREATE POLICY "Public products access" ON public.products FOR ALL USING (true);
CREATE POLICY "Public orders access" ON public.orders FOR ALL USING (true);
CREATE POLICY "Public support_tickets access" ON public.support_tickets FOR ALL USING (true);
