-- ============================================================
-- AerLaut (JaringLokal) Online Marketplace Database Schema
-- Robust & Safe SQL Script for Supabase PostgreSQL SQL Editor
-- ============================================================

-- ------------------------------------------------------------
-- STEP 1: CREATE ALL TABLES FIRST
-- ------------------------------------------------------------

-- 1. Create Users Table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT,
  role TEXT DEFAULT 'customer',
  auth_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure role column exists if users table was created previously
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'customer';

-- Link profile rows to Supabase Auth (auth.users). Required so that OTP
-- verification emails on signup/reset actually get sent by Supabase —
-- a plain insert into this table alone never triggers an email.
ALTER TABLE public.users ADD COLUMN IF NOT EXISTS auth_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_users_auth_id ON public.users(auth_id);

-- Password is now managed & hashed by Supabase Auth, not stored here in
-- plaintext. Loosen the old NOT NULL constraint for tables created before
-- this change.
ALTER TABLE public.users ALTER COLUMN password DROP NOT NULL;

-- 2. Create Stores Table
CREATE TABLE IF NOT EXISTS public.stores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  store_name TEXT NOT NULL,
  description TEXT,
  address TEXT,
  phone TEXT,
  status TEXT DEFAULT 'approved',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Products Table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id BIGINT REFERENCES public.stores(id) ON DELETE SET NULL,
  store_name TEXT DEFAULT 'Toko Nelayan Bahari Pak Bambang',
  name TEXT NOT NULL,
  price NUMERIC NOT NULL,
  category TEXT NOT NULL,
  stock INT DEFAULT 0,
  image TEXT,
  unit TEXT DEFAULT 'kg',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Ensure store columns exist if products table was created previously
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS store_id BIGINT REFERENCES public.stores(id) ON DELETE SET NULL;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS store_name TEXT DEFAULT 'Toko Nelayan Bahari Pak Bambang';

-- 4. Create Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_name TEXT NOT NULL,
  total_amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'Menunggu Konfirmasi',
  items JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------
-- STEP 2: SEED INITIAL DATA
-- ------------------------------------------------------------

-- Seed Initial Users
-- IDs are assigned explicitly (not left to auto-increment) because the
-- stores/products seed data below hardcodes user_id/store_id values that
-- must match. Relying on auto-increment breaks as soon as the users table
-- already has any rows (e.g. from real registrations), since ON CONFLICT
-- (email) would then skip the insert while id=2/3 still wouldn't exist.
INSERT INTO public.users (id, name, email, password, role)
VALUES 
  (1, 'Admin JaringLokal', 'admin@jaringlokal.com', 'admin123', 'admin'),
  (2, 'Pak Bambang Nelayan', 'bambang@jaringlokal.com', 'seller123', 'seller'),
  (3, 'Ibu Siti Olahan Laut', 'siti@jaringlokal.com', 'seller123', 'seller')
ON CONFLICT (id) DO NOTHING;

-- Keep the auto-increment sequence in sync so future inserts (real user
-- registrations) don't collide with the hardcoded seed IDs above.
SELECT setval(
  pg_get_serial_sequence('public.users', 'id'),
  GREATEST((SELECT COALESCE(MAX(id), 0) FROM public.users), 1)
);

-- Seed Initial Stores
INSERT INTO public.stores (id, user_id, store_name, description, address, phone, status)
VALUES
  (1, 2, 'Toko Nelayan Bahari Pak Bambang', 'Penyedia hasil laut segar langsung dari tangkapan nelayan pesisir Tuban.', 'Jl. Pesisir Pantai Kradenan No. 12, Tuban', '081234567890', 'approved'),
  (2, 3, 'Dapur Olahan Laut Ibu Siti', 'Olahan khas ikan asap, terasi super, dan bandeng presto higienis.', 'Jl. Raya Nelayan No. 45, Tuban', '089876543210', 'approved')
ON CONFLICT (id) DO NOTHING;

-- Seed Initial Products
INSERT INTO public.products (id, store_id, store_name, name, price, category, stock, image, unit) VALUES
(1, 2, 'Dapur Olahan Laut Ibu Siti', 'Terasi Pesisir Tuban', 25000, 'Olahan', 50, 'https://images.unsplash.com/photo-1621317762692-0f04f2f53472?auto=format&fit=crop&q=80&w=400', 'bungkus'),
(2, 1, 'Toko Nelayan Bahari Pak Bambang', 'Rajungan Segar', 85000, 'Tangkapan Segar', 20, 'https://images.unsplash.com/photo-1599839619722-39751411ea63?auto=format&fit=crop&q=80&w=400', 'kg'),
(3, 2, 'Dapur Olahan Laut Ibu Siti', 'Ikan Asap Tuban', 35000, 'Olahan', 30, 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&q=80&w=400', 'kg'),
(4, 1, 'Toko Nelayan Bahari Pak Bambang', 'Cumi-cumi Segar', 60000, 'Tangkapan Segar', 40, 'https://images.unsplash.com/photo-1559868725-b467ec6a6d0c?auto=format&fit=crop&q=80&w=400', 'kg'),
(5, 1, 'Toko Nelayan Bahari Pak Bambang', 'Udang Vaname Segar', 75000, 'Tangkapan Segar', 35, 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&q=80&w=400', 'kg'),
(6, 1, 'Toko Nelayan Bahari Pak Bambang', 'Ikan Kerapu Merah', 120000, 'Tangkapan Segar', 8, 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=400', 'kg'),
(7, 1, 'Toko Nelayan Bahari Pak Bambang', 'Kerang Hijau', 30000, 'Tangkapan Segar', 60, 'https://images.unsplash.com/photo-1569385210018-127685f22b5a?auto=format&fit=crop&q=80&w=400', 'kg'),
(8, 2, 'Dapur Olahan Laut Ibu Siti', 'Bandeng Presto', 45000, 'Olahan', 25, 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&q=80&w=400', 'ekor')
ON CONFLICT (id) DO NOTHING;

-- ------------------------------------------------------------
-- STEP 3: ENABLE RLS & CREATE PUBLIC POLICIES
-- ------------------------------------------------------------

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public users access" ON public.users;
DROP POLICY IF EXISTS "Public stores access" ON public.stores;
DROP POLICY IF EXISTS "Public products access" ON public.products;
DROP POLICY IF EXISTS "Public orders access" ON public.orders;

CREATE POLICY "Public users access" ON public.users FOR ALL USING (true);
CREATE POLICY "Public stores access" ON public.stores FOR ALL USING (true);
CREATE POLICY "Public products access" ON public.products FOR ALL USING (true);
CREATE POLICY "Public orders access" ON public.orders FOR ALL USING (true);
