import pkg from 'pg';
const { Pool } = pkg;

// Standard Direct Connection Host & Port 5432
const connectionString = process.env.DATABASE_URL || 'postgresql://postgres:%40Rengga123_@db.zkywxhgcdkixufpxlnwi.supabase.co:5432/postgres';

async function setupDatabase() {
  console.log('🔌 Attempting direct connection to PostgreSQL Supabase database (db.zkywxhgcdkixufpxlnwi.supabase.co:5432)...');
  
  const pool = new Pool({
    connectionString,
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 10000,
  });

  try {
    const client = await pool.connect();
    console.log('✅ Connected successfully!');

    // 1. Create products table
    console.log('📦 Creating "products" table...');
    await client.query(`
      CREATE TABLE IF NOT EXISTS products (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        price NUMERIC NOT NULL,
        category TEXT NOT NULL,
        stock INT DEFAULT 0,
        image TEXT,
        unit TEXT DEFAULT 'kg',
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // 2. Create orders table
    console.log('🛒 Creating "orders" table...');
    await client.query(`
      CREATE TABLE IF NOT EXISTS orders (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_name TEXT NOT NULL,
        total_amount NUMERIC NOT NULL,
        status TEXT DEFAULT 'Menunggu Konfirmasi',
        items JSONB DEFAULT '[]'::jsonb,
        created_at TIMESTAMPTZ DEFAULT NOW()
      );
    `);

    // 3. Seed initial products
    const res = await client.query('SELECT COUNT(*) FROM products;');
    const count = parseInt(res.rows[0].count, 10);
    if (count === 0) {
      console.log('🌱 Seeding initial product data...');
      const initialProducts = [
        { name: 'Terasi Pesisir Tuban', price: 25000, category: 'Olahan', stock: 50, image: 'https://images.unsplash.com/photo-1621317762692-0f04f2f53472?auto=format&fit=crop&q=80&w=400', unit: 'bungkus' },
        { name: 'Rajungan Segar', price: 85000, category: 'Tangkapan Segar', stock: 20, image: 'https://images.unsplash.com/photo-1599839619722-39751411ea63?auto=format&fit=crop&q=80&w=400', unit: 'kg' },
        { name: 'Ikan Asap Tuban', price: 35000, category: 'Olahan', stock: 30, image: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?auto=format&fit=crop&q=80&w=400', unit: 'kg' },
        { name: 'Cumi-cumi Segar', price: 60000, category: 'Tangkapan Segar', stock: 40, image: 'https://images.unsplash.com/photo-1559868725-b467ec6a6d0c?auto=format&fit=crop&q=80&w=400', unit: 'kg' },
        { name: 'Udang Vaname Segar', price: 75000, category: 'Tangkapan Segar', stock: 35, image: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&q=80&w=400', unit: 'kg' },
        { name: 'Ikan Kerapu Merah', price: 120000, category: 'Tangkapan Segar', stock: 8, image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=400', unit: 'kg' },
        { name: 'Kerang Hijau', price: 30000, category: 'Tangkapan Segar', stock: 60, image: 'https://images.unsplash.com/photo-1569385210018-127685f22b5a?auto=format&fit=crop&q=80&w=400', unit: 'kg' },
        { name: 'Bandeng Presto', price: 45000, category: 'Olahan', stock: 25, image: 'https://images.unsplash.com/photo-1510130387422-82bed34b37e9?auto=format&fit=crop&q=80&w=400', unit: 'ekor' }
      ];

      for (const prod of initialProducts) {
        await client.query(
          `INSERT INTO products (name, price, category, stock, image, unit) VALUES ($1, $2, $3, $4, $5, $6);`,
          [prod.name, prod.price, prod.category, prod.stock, prod.image, prod.unit]
        );
      }
      console.log('✅ Initial products seeded successfully!');
    } else {
      console.log(`ℹ️ Products table already has ${count} records.`);
    }

    client.release();
    await pool.end();
  } catch (err) {
    console.error('❌ Connection failed via direct TCP socket port 5432/6543.');
    console.error('Reason:', err.message);
    console.log('\n💡 TIP: Local ISP/Firewall often blocks direct DB ports 5432 & 6543.');
    console.log('Please copy-paste the SQL script from README-DATABASE.md directly into Supabase Dashboard SQL Editor!');
  }
}

setupDatabase();
